name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    # @see https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#concurrency
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.os }}-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/initialize
      - uses: mlugg/setup-zig@v1
      - run: |
          zig build test
