name: Release Workflow

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: ./.github/actions/initialize
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - name: Zig Build and Test
        run: |
          zig version
          zig build
        env:
          TAG_NAME: ${{ github.ref_name }}

      - name: Archive Build Artifact
        run: |
          mkdir -p artifacts
          cp zig-out/bin/* artifacts/

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
