name: Release Workflow

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: ./.github/actions/initialize
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - name: Zig Build and Test
        # node -e "console.log(`\${process.platform}-\${process.arch}`)"
        run: |
          zig version
          zig build
        env:
          TAG_NAME: ${{ github.ref_name }}

      - name: Archive Build Artifact
        run: |
          mkdir -p artifacts
          zip -r zag.zip ./zig-out/bin/
          mv zag-{os}-{arch}.zip artifacts/

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.event.pull_request.body }}
          tag_name: ${{ github.event.pull_request.title }}
          generate_release_notes: true
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
